seed: 0
optimizer: re
search_space: nasbench201
dataset: cifar10
out_dir: run

search:
  checkpoint_freq: 1000
  epochs: 1000
  fidelity: -1

  zc_names: snip
  predictor_type: zc
  predictor: snip
  num_init: 10  
  k: 10

  # RE
  sample_size: 5
  population_size: 50
  
  # jacov data loader
  batch_size: 256
  data_size: 25000
  cutout: False
  cutout_length: 16
  cutout_prob: 1.0
  train_portion: 0.7
  
  # other params
  debug_predictor: False
  sample_size: 10
  population_size: 30
